apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-next-js-app-deployment
  labels:
    app: my-next-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-next-js-app
  template:
    metadata:
      labels:
        app: my-next-js-app
    spec:
      containers:
        - name: my-next-js-app
          image: my-next-js-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          # env:
          #   - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongodb-secret
          #         key: mongo-root-username
          #   - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongodb-secret
          #         key: mongo-root-password
          #   - name: ME_CONFIG_MONGODB_SERVER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: mongodb-configmap
          #         key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: my-next-js-app-service
spec:
  selector:
    app: my-next-js-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-next-js-app
#   labels:
#     run: my-next-js-app
# spec:
#   type: NodePort
#   ports:
#     - port: 8081
#       protocol: TCP
#   selector:
#     run: my-next-js-app
